name: precious

on:
  push:
  pull_request:

permissions: {}

jobs:
  precious:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@9149ea85001c7435d5a66bb127d6a1b6227cb0a5 # v5.0.0
        with:
          cache: true

      - name: Run precious lint
        run: precious lint --all
